### ISSUE TITLE
@tourism:hotel "new york"

### ISSUE THREAD

**Issue by d1g** [dbahrdt/oscar-web#1]
from https://github.com/dbahrdt/oscar-web/blob/4d54325b627203669f38e09aba20b4f0e62266c5/website/template/help.html#L166

```
 @tourism:hotel "new york"
 List all hotels in New York
```

but [@shop:clothes "Москва"](http://oscar.fmi.uni-stuttgart.de/?q=%40shop%3Aclothes%20%22%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0%22) will return 812 results in Russia but also [this node in Kazachstan](http://www.openstreetmap.org/node/2049363634/history) too, something is inaccurate here.

Inaccurate docs?

**Comment by dbahrdt** [comment]
Hi,
this is actually correct. Since the node is named Москва. Oscar currently does not try to find out if a query statement should only match regions. Oscardev has additional syntax to do that. @shop:clothes #"Москва" matches only regions with the exact name Москва. But there are indeed some more bugs in oscardev which I currently track in my todo list. Maybe I should track them as github issues if this gets more public exposure.
